### ISSUE TITLE
Optional fallback support for missing or unknown SNI hostname

### ISSUE THREAD

**Issue by spacesynth** [atenart/sniproxy#6]
Great server! Very fast and stable for me. There is some improvement possible:

```
routes:
- fallback:
  backend:
    address: "127.0.0.1:3443"
- domains:
  - "example.net"
  backend:
    address: "1.2.3.4:443"
```

Clients or bots not sending SNI hostname or an unknown one in message are a completely normal thing. This should not be an error. Instead the loglevel should raise only (Debug) on clients with no SNI field or hostname. So we can handle them better.

Imagine
```(Debug) Client sent empty or unknown SNI hostname, taking the fallback route```

If an optional fallback server was defined on a custom IP:PORT by the user, we send all requests with empty or unknown SNI hostname there.

What do you think?
